### ISSUE TITLE
Conda release / which version used in bcbio

### ISSUE THREAD

**Issue by schelhorn** [roryk/ipython-cluster-helper#45]
Hello @roryk, I was wondering which version of the cluster-helper is installed with bcbio since I do not seem to get the newest cluster-helper (the one with `--local_controller`) when I update bcbio. Is that due to the bcbio dependency list not asking for the newest cluster-helper, or because there is a conda release missing? Thank you.

**Comment by chapmanb** [comment]
Sven-Eric -- sorry about the problem, I have a fix in PR to resolve this issue:

https://github.com/bioconda/bioconda-recipes/pull/3079/files#diff-7612dac13b6b8b12b057806fd73be8c4R35

but Travis is having infrastructure issues right now so we're having trouble pushing through the conda packages with the fix.

The problem is that we pinned ipython-cluster-helper to require ipython 4.0 after v0.5.1 so conda resolution unhelpfully installs ipython 5.0 dependencies and older version of ipython-cluster-helper instead of recent versions of ipython-cluster-helper and older versions of ipython as we intended. I hope that package will get pushed today and we'll now do the right thing.

In the short term you can do:
```
bcbio_conda install -c bioconda ipython-cluster-helper
```
to get the latest. Hope this helps.

**Comment by schelhorn** [comment]
Great, thanks.
